<a href="https://colab.research.google.com/github/ikeda740/pro2_sample/blob/main/sandbox.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = [True, False, True, False]
b = [True, True, False, True]

c = a|b
print(c)

TypeError: ignored

In [ ]:
import numpy as np
a = np.zeros((2,3))
print(a)
a[1][2] = 1.0
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 1.]]


In [ ]:
%%file file.csv
A,B,C
2,0,1
4,0,0
8,1,1
9,1,0

Overwriting file.csv


In [ ]:
import pandas as pd

filename = "file.csv"
df = pd.read_csv(filename)
print(df)
print("")

print(df.C==1)
print("")

df1 = df[df.C==1]
print(df1)
print("")

for t in df1.A:
  print(t)

   A  B  C
0  2  0  1
1  4  0  0
2  8  1  1
3  9  1  0

0     True
1    False
2     True
3    False
Name: C, dtype: bool

   A  B  C
0  2  0  1
2  8  1  1

2
8
